### PR TITLE
default proxy to http:// if necessary, fixes #1282

### LINKED ISSUE #1282: Proxy silently ignored without `http:`
## Basic Info

* Faraday Version: 1.4.1
* Ruby Version: 2.7

## Issue description

Proxy silently ignored without `http:`. For example, if you set proxy to `something:1234` it will be silently ignored. The correct proxy setting would be `http://something:1234`. This is an important issue because it's undocumented, difficult to debug, and can have serious consequences for crawling projects.

I propose either:

1. In ProxyOptions.from, reject strings that lack a scheme.
or
1. In ProxyOptions.from, default to `http://` for strings that lack a scheme.

Let me know if you agree with one of these options and I'l put together a PR. Thanks!

## Steps to reproduce

```ruby
> Faraday::ProxyOptions.from("something:1234").host
# => nil

> Faraday::ProxyOptions.from("http://something:1234").host
# => "something"
```

### PR DESCRIPTION
**Pull request by gurgeous**
Previously, the proxy setting was silently ignored if you accidentally left off the scheme (`something:1234`). This change fills in the `http://` if it seems to be missing. Fixes #1282.

### CODE REVIEW

File: lib/faraday/options/proxy_options.rb [hunk 1]
```diff
@@ -19,6 +19,13 @@ def self.from(value)
           value[:uri] = Utils.URI(uri)
         end
       end
+
+      # URIs without a scheme should default to http (like 'example:123'). This
+      # fixes #1282 and prevents a silent failure in some adapters.
+      if value && !value[:uri].to_s.include?('://')
+        value[:uri] = Utils.URI("http://#{value[:uri]}")
+      end
```
Comment (iMacTia) [inline lib/faraday/options/proxy_options.rb:27]: What do you think of having this check only in the `case when String` branch?
That looks like the most common use case, and if a `URI` or `Options` object is provided then probably the caller knows what they're doing (leaving the door open to override this automatic fix, if necessary)

Comment (gurgeous) [reply lib/faraday/options/proxy_options.rb]: Good idea - how about this?

**Review by iMacTia — APPROVED** [review]

**Comment by iMacTia** [comment]
Thanks @gurgeous, this looks great! 🎉
