### PR TITLE
Make dig method case-insensitive in Faraday::Utils::Headers

### LINKED ISSUE #1556: Case Insensitivity Issue with #dig Method on Response Headers
## Basic Info

* Faraday Version: 2.9.0
* Ruby Version: 3.1.2

## Issue description
I've encountered an issue with the case-insensitive [Hash](https://github.com/lostisland/faraday/blob/main/lib/faraday/utils/headers.rb) which is used as a response headers container. While the case insensitivity works as expected when accessing headers using `#[]`, it fails when using the `#dig` method. Rack handles this properly: https://github.com/rack/rack/blob/8c73aefcc7085c71bdfe6c1ec867f126ede34124/lib/rack/headers.rb#L131-L133

## Steps to reproduce
```ruby
require 'faraday'

response = Faraday.get('http://httpbingo.org')

pp response.headers.dig('via') # "1.1 fly.io"
pp response.headers.dig('Via') # nil
```

### PR DESCRIPTION
**Pull request by vitali-semenyuk**
## Description
Adds `#dig` method to Faraday::Utils::Headers to keep Hash access methods consistent

Fixes #1556 

## Todos
List any remaining work that needs to be done, i.e:
- [x] Tests
- [ ] Documentation

### CODE REVIEW

File: spec/faraday/utils/headers_spec.rb [hunk 1]
```diff
@@ -56,6 +56,15 @@
     it { expect(subject.delete('content-type')).to be_nil }
   end
 
+  describe '#dig' do
+    before { subject['Content-Type'] = 'application/json' }
+
+    it { expect(subject&.dig('Content-Type')).to eq('application/json') }
+    it { expect(subject&.dig('CONTENT-TYPE')).to eq('application/json') }
+    it { expect(subject&.dig(:content_type)).to eq('application/json') }
+    it { expect(subject&.dig('invalid')).to be_nil }
```
Comment (olleolleolle) [inline spec/faraday/utils/headers_spec.rb:65]: The safe-navigation operator is not needed here.

(The use of the `subject` dynamic definition's superfluous, too, but make no changes to that in this PR.)

**Review by olleolleolle — APPROVED** [review]
Thanks!

:hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:
